<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OtherFlags></OtherFlags>
    <DocumentationFile></DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="imgs\Chess_bdd44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_bdl44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_bld44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_bll44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_d44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_kdd44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_kdl44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_kld44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_kll44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_l44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_ndd44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_ndl44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_nld44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_nll44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_pdd44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_pdl44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_pld44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_pll44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_qdd44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_qdl44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_qld44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_qll44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_rdd44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_rdl44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_rld44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="imgs\Chess_rll44.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="Types.fs" />
    <Compile Include="Util.fs" />
    <Compile Include="Direction.fs" />
    <Compile Include="Player.fs" />
    <Compile Include="PieceType.fs" />
    <Compile Include="Piece.fs" />
    <Compile Include="Rank.fs" />
    <Compile Include="File.fs" />
    <Compile Include="Square.fs" />
    <Compile Include="GameResult.fs" />
    <Compile Include="DateUtil.fs" />
    <Compile Include="NagUtil.fs" />
    <Compile Include="Stats.fs" />
    <Compile Include="BitBoard.fs" />
    <Compile Include="Attacks.fs" />
    <Compile Include="FEN.fs" />
    <Compile Include="Move.fs" />
    <Compile Include="Board.fs" />
    <Compile Include="Png.fs" />
    <Compile Include="MoveGenerate.fs" />
    <Compile Include="PgnWrite.fs" />
    <Compile Include="pMove.fs" />
    <Compile Include="MoveTextEntry.fs" />
    <Compile Include="Game.fs" />
    <Compile Include="MoveUtil.fs" />
    <Compile Include="RegParse.fs" />
    <Compile Include="Games.fs" />
    <Compile Include="PgnWriter.fs" />
    <Compile Include="Stockfish.fs" />
    <Compile Include="FsChess.fs" />
    <Compile Include="FsChess.Pgn.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
  </ItemGroup>

</Project>
